In [1]:
import numpy as np
m1=np.array([[12,13],[14,16]])
m2=np.array([[18,19],[20,21]])
a=np.hstack((m1,m2))
b=np.vstack((m1,m2))
print("hstack is",a)
print("vstack is",a)

hstack is [[12 13 18 19]
 [14 16 20 21]]
vstack is [[12 13 18 19]
 [14 16 20 21]]


In [2]:
import numpy as np
a1=np.array([[1,2,3,4],[5,6,7,8]])
a2=np.array([[100,200,300,400],[500,600,700,800]])
print("the array is",a1)
print("the array is",a2)

the array is [[1 2 3 4]
 [5 6 7 8]]
the array is [[100 200 300 400]
 [500 600 700 800]]


In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4])

print("shape a:{}".format(a.shape))
print("ndim {}".format(a.ndim))
print("size {}".format(a.size))
print(f"dtype {a.dtype}")
print(f"itemsize {a.itemsize}")
print(f"data {a.data}")

shape a:(5,)
ndim 1
size 5
dtype int64
itemsize 8
data <memory at 0x7fb06ee50640>


In [4]:
a1=np.array([[2,3,4,5],
             [1,4,7,6]])
a2=np.array([[1,1,1],[1,1,1]])
#add(), subtract(),mod(),reminder(),multiply(),divide(), power(),absolute()


sliced_arr=a1[:2,:2]
print(sliced_arr)

[[2 3]
 [1 4]]


In [5]:
index_arr=a1[[1,1],[2,1]]
print(index_arr)

[7 4]


In [6]:
print(a1.sum())

32


In [7]:
arr=np.array([[25,64],[89,36]])
print(arr.sum())


214


In [8]:
print(np.sqrt(arr))

[[5.         8.        ]
 [9.43398113 6.        ]]


In [9]:
print(arr.T)

[[25 89]
 [64 36]]


In [10]:
b1=np.array([[2,3],[4,5]])
b2=np.array([[5,6],[7,8]])
matrix_multi=np.dot(b1,b2)
print(matrix_multi)

[[31 36]
 [55 64]]


In [11]:
bool=np.array([[True,True],[False,True]])
print("all() with axis none",np.all(bool))
print("all() with axis 0",np.all(bool,axis=0))#any()


all() with axis none False
all() with axis 0 [False  True]


In [12]:
temp=np.arange(9)
print(temp)
re=temp.reshape(3,3)
print(re)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
print(np.take(re,[0,1],axis=1))

[[0 1]
 [3 4]
 [6 7]]


In [14]:
x=np.array([[12,23],[23,34]])
y=np.array([[56,67],[78,89]])
z=np.array([[32,43],[54,65]])
v=np.vstack((x,y,z))
h=np.hstack((x,y,z))

print("vstack:",v)
print("hstack:",h)

vstack: [[12 23]
 [23 34]
 [56 67]
 [78 89]
 [32 43]
 [54 65]]
hstack: [[12 23 56 67 32 43]
 [23 34 78 89 54 65]]


In [15]:
h_split=np.hsplit(h,3)
print("split:",split)
v_split=np.vsplit(h,2)
print("vsplit:",v_split)

NameError: name 'split' is not defined

In [17]:
h_split=np.hsplit(h,3)
print("split:",split)
v_split=np.vsplit(h,2)
print("vsplit:",v_split)

NameError: name 'hsplit' is not defined

In [18]:
arr=np.array([23,34,45,67])
print("Sqrt: ",np.sqrt(arr))#Returns the square root of each element 
print("Exp: ",np.exp(arr))     #Returns the exponentials of each element
print("Sin: ",np.sin(arr))     #Returns the sin of each element
print("Cos: ",np.cos(arr))     #Returns the cosine of each element
print("Log: ",np.log(arr))     #Returns the logarithm of each element
print("Sum: ",np.sum(arr))     #Returns the sum total of elements in the array
print("Std: ",np.std(arr))     #Returns the standard deviation of in the array

Sqrt:  [4.79583152 5.83095189 6.70820393 8.18535277]
Exp:  [9.74480345e+09 5.83461743e+14 3.49342711e+19 1.25236317e+29]
Sin:  [-0.8462204   0.52908269  0.85090352 -0.85551998]
Cos:  [-0.53283302 -0.84857027  0.52532199 -0.5177698 ]
Log:  [3.13549422 3.52636052 3.80666249 4.20469262]
Sum:  169
Std:  16.269219403523945


In [19]:
print("random: {}\n".format(np.random.random(20)));

print("rand: {}\n".format(np.random.rand(3, 4)));

print("randint: {}\n".format(np.random.randint(0, 100, 20)));

print("permutation: {}\n".format(np.random.permutation(np.arange(20))));

random: [0.01934241 0.32774664 0.44627303 0.56500232 0.18175561 0.08567501
 0.33431118 0.18413079 0.95056075 0.04046635 0.77503871 0.94082527
 0.8910562  0.28671942 0.91095767 0.43954648 0.37776774 0.61034339
 0.77744796 0.00584605]

rand: [[0.09789323 0.33866893 0.24281881 0.07913589]
 [0.81969619 0.20285784 0.30920636 0.02667197]
 [0.16960974 0.34793114 0.58689872 0.2347141 ]]

randint: [67 56 93 38 70 58 41 22 70 46 13 20 93 85  0 57 93 76 75 80]

permutation: [10 14 18  7 17  4 11 13  5 16 12  1  9 19  0  8 15  2  6  3]

